# Site settings
# in the templates available like {{ site.myvariable }}.
title: Em Prol da Regeneração de Gaia
email: fluxoterra@gmail.com
brand: Fluxo Terra
headline: Reconexão, Regeneração
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://fluxoterra.github.io" # the base hostname & protocol for your site
copyright: 2016 Whatever Company, Inc. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: fluxoterra@gmail.com
phone:

# Tracking
googleAnalitycsID: UA-83933844-1

